### ISSUE TITLE
NoMethodError on beta3

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd-regression-tester#40]
Travis builds on master are failing due to:

```
/home/travis/.rvm/gems/ruby-2.4.1/gems/pmdtester-1.0.0.pre.beta3/lib/pmdtester/project.rb:107:in `introduce_new_errors?': undefined method `introduce_new_errors?' for nil:NilClass (NoMethodError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/pmdtester-1.0.0.pre.beta3/lib/pmdtester/runner.rb:123:in `block in introduce_new_pmd_error?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/pmdtester-1.0.0.pre.beta3/lib/pmdtester/runner.rb:122:in `each'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/pmdtester-1.0.0.pre.beta3/lib/pmdtester/runner.rb:122:in `introduce_new_pmd_error?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/pmdtester-1.0.0.pre.beta3/lib/pmdtester/runner.rb:21:in `run'
	from /home/travis/.rvm/gems/ruby-2
```

See https://travis-ci.org/pmd/pmd/jobs/420906078#L6558-L6563

**Comment by djydewang** [comment]
@jsotuyod I've fixed the bug. But the https://github.com/pmd/pmd repository can't get feedback right away until we fix https://github.com/pmd/pmd-regression-tester/issues/42
